# 1. Import the necessary libraries.

In [8]:
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold, cross_val_score
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from time import time
from IPython.display import display  # Allows the use of display() for DataFrames

In [9]:
# Loading the dataset
#data = pd.read_csv("preprocessed_data.csv")

# Display 3 records.
#display(data.head(n=3))

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Columns: 2153 entries, Plant ID to Treatment
dtypes: float64(2151), int64(2)
memory usage: 9.3 MB


In [10]:
#data.describe()

# 2. Accuracy Scores Before Cross Validation Using Train Test Split:

## Supervised ML Models:
## *1. AdaBoost Classifier
## *2. Random Forest Classifier
## *3. Decision Trees Classifier
## *4. Logistic Regression

In [5]:
features = data.drop(['Plant ID','Treatment'], axis = 1)
target = data["Treatment"]
groups = list(data["Plant ID"])

In [7]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Splitting the 'features' and 'target' data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, 
                                                    target, 
                                                    test_size = 0.1,
                                                   random_state = 101)

# Showing the results of the split
print("Training set has {} samples.".format(X_train.shape[0]))
print("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 510 samples.
Testing set has 57 samples.


### 1- AdaBoost

In [7]:
clf_B = AdaBoostClassifier(n_estimators= 500,learning_rate=1)
clf_B.fit(X_train,y_train)
predictions = clf_B.predict(X_test)
print(accuracy_score(y_test,predictions))

0.9473684210526315


### 2- Random Forest

In [8]:
clf_A = RandomForestClassifier(n_estimators= 600)
clf_A.fit(X_train,y_train)
predictions = clf_A.predict(X_test)
print(accuracy_score(y_test,predictions))

0.8596491228070176


### 3- Decision Trees

In [9]:
clf_G = DecisionTreeClassifier()
clf_G.fit(X_train,y_train)
predictions = clf_G.predict(X_test)
print(accuracy_score(y_test,predictions))

0.8421052631578947


### 4- Logistic Regression

In [10]:
clf_E = LogisticRegression(solver='liblinear',multi_class='auto')
clf_E.fit(X_train,y_train)
predictions = clf_E.predict(X_test)
print(accuracy_score(y_test,predictions))

0.8947368421052632


# 3. Accuracy Scores Using:

## *Method1: K-Fold Cross Validation
## *Method2: Group K-Fold Cross Validation

In [11]:
features = data.drop(['Plant ID','Treatment'], axis = 1)
target = data["Treatment"]
print("The unique number of plant ids are {}".format(data['Plant ID'].nunique()))
groups = list(data["Plant ID"])

The unique number of plant ids are 63


## Method 1: "Group K-fold CV" no overlapping but samples sequence is shuffled. 

In [12]:
gkf = GroupKFold(n_splits=63)
gkf

GroupKFold(n_splits=63)

In [13]:
cnt = 1
for train_index , test_index in gkf.split(features, target, groups=groups):
    print("\n Train Indeces:", train_index , "\n \n  Validation Indeces:",test_index)
    print("\n")
    print(f'Fold:{cnt}, Train set samples: {len(train_index)}, Test set samples:{len(test_index)}')
    cnt += 1


 Train: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 2

## Method 2: "K-fold CV" no overlapping and samples sequence is not shuffled. 

In [14]:
kf = KFold(n_splits=63)
kf

KFold(n_splits=63, random_state=None, shuffle=False)

In [15]:
cnt = 1
for train_index , test_index in kf.split(features, target):
    print("\n Train Indeces:", train_index , "\n \n  Validation Indeces:",test_index)
    print("\n")
    print(f'Fold:{cnt}, Train set samples: {len(train_index)}, Test set samples:{len(test_index)}')
    cnt += 1


 Train: [  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26
  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44
  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62
  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 2

## 3.1 Create a function and a for loop to get the accuracy scores through all the K-Fold CV itterations.

In [16]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [17]:
scores_ab = [] # Accuracy Scores of AdaBoost Classifier
scores_dt = [] # Accuracy Scores of Decision Trees Classifier
scores_rf = [] # Accuracy Scores of Random Forest Classifier
scores_lr = [] # Accuracy Scores of Logistic Regression Classifier

for train_index , test_index in kf.split(np.array(features), np.array(target)):
    X_train, X_test, y_train, y_test =  np.array(features)[train_index] , np.array(features)[test_index] , np.array(target)[train_index], np.array(target)[test_index]
    
    scores_ab.append(get_score(AdaBoostClassifier(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
    scores_lr.append(get_score(LogisticRegression(solver='liblinear',multi_class='auto'), X_train, X_test, y_train, y_test))
    
    
    


## 1- Accuracy Scores of AdaBoost Classifier

In [18]:
scores_ab

[0.4444444444444444,
 0.8888888888888888,
 0.7777777777777778,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7777777777777778,
 1.0,
 1.0,
 1.0,
 0.8888888888888888,
 1.0,
 0.8888888888888888,
 0.6666666666666666,
 0.5555555555555556,
 0.5555555555555556,
 0.6666666666666666,
 0.8888888888888888,
 1.0,
 1.0,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.3333333333333333,
 0.8888888888888888,
 0.7777777777777778,
 0.6666666666666666,
 1.0,
 0.7777777777777778,
 0.4444444444444444,
 1.0,
 0.4444444444444444,
 0.6666666666666666,
 1.0,
 0.7777777777777778,
 0.8888888888888888,
 0.7777777777777778,
 0.6666666666666666,
 0.7777777777777778,
 0.5555555555555556,
 0.8888888888888888,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.7777777777777778,
 0.2222222222222222,
 1.0,
 0.6666666666666666,
 0.8888888888888888,
 0.3333333333333333,
 0.7777777777777778,
 0.5555555555555556,
 0.8888888888888888,
 0.0,
 0.0,
 1.0]

## 2- Accuracy Scores of Random Forest Classifier

In [19]:
scores_rf

[0.3333333333333333,
 1.0,
 0.8888888888888888,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8888888888888888,
 0.6666666666666666,
 1.0,
 1.0,
 0.8888888888888888,
 0.8888888888888888,
 0.7777777777777778,
 1.0,
 0.8888888888888888,
 0.7777777777777778,
 1.0,
 0.6666666666666666,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7777777777777778,
 0.8888888888888888,
 0.8888888888888888,
 0.4444444444444444,
 0.4444444444444444,
 0.6666666666666666,
 0.5555555555555556,
 0.8888888888888888,
 1.0,
 0.8888888888888888,
 1.0,
 0.6666666666666666,
 0.3333333333333333,
 0.8888888888888888,
 0.7777777777777778,
 1.0,
 1.0,
 1.0,
 0.5555555555555556,
 0.7777777777777778,
 1.0,
 1.0,
 1.0,
 0.0,
 0.8888888888888888,
 1.0,
 0.1111111111111111,
 1.0,
 0.7777777777777778,
 0.1111111111111111,
 1.0,
 0.6666666666666666,
 0.8888888888888888,
 0.4444444444444444,
 1.0,
 0.7777777777777778,
 0.8888888888888888,
 0.0,
 0.0,
 0.8888888888888888]

## 3- Accuracy Scores of Decision Trees Classifier

In [20]:
scores_dt

[0.4444444444444444,
 0.7777777777777778,
 0.7777777777777778,
 1.0,
 0.8888888888888888,
 1.0,
 1.0,
 0.7777777777777778,
 0.7777777777777778,
 0.5555555555555556,
 0.7777777777777778,
 0.7777777777777778,
 0.2222222222222222,
 0.6666666666666666,
 0.7777777777777778,
 0.8888888888888888,
 0.7777777777777778,
 1.0,
 0.5555555555555556,
 0.5555555555555556,
 1.0,
 1.0,
 0.7777777777777778,
 0.6666666666666666,
 0.6666666666666666,
 0.8888888888888888,
 0.2222222222222222,
 0.6666666666666666,
 0.7777777777777778,
 0.7777777777777778,
 1.0,
 0.7777777777777778,
 0.5555555555555556,
 1.0,
 0.4444444444444444,
 0.6666666666666666,
 0.7777777777777778,
 0.7777777777777778,
 0.8888888888888888,
 0.6666666666666666,
 0.8888888888888888,
 0.6666666666666666,
 0.6666666666666666,
 0.7777777777777778,
 0.8888888888888888,
 1.0,
 0.1111111111111111,
 0.8888888888888888,
 0.7777777777777778,
 0.1111111111111111,
 1.0,
 0.6666666666666666,
 0.3333333333333333,
 0.8888888888888888,
 0.5555555555555

## 4- Accuracy Scores of Logistic Regression Classifier

In [21]:
scores_lr

[0.4444444444444444,
 0.8888888888888888,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.2222222222222222,
 0.8888888888888888,
 1.0,
 1.0,
 0.7777777777777778,
 0.4444444444444444,
 0.5555555555555556,
 1.0,
 1.0,
 1.0,
 0.4444444444444444,
 1.0,
 0.6666666666666666,
 1.0,
 0.3333333333333333,
 1.0,
 1.0,
 1.0,
 0.3333333333333333,
 1.0,
 0.5555555555555556,
 0.6666666666666666,
 0.7777777777777778,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7777777777777778,
 1.0,
 1.0,
 0.7777777777777778,
 1.0,
 0.8888888888888888,
 1.0,
 0.6666666666666666,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.3333333333333333,
 1.0,
 1.0,
 0.0,
 0.7777777777777778,
 1.0,
 1.0,
 0.7777777777777778,
 1.0,
 0.6666666666666666,
 1.0,
 0.0,
 0.0,
 1.0]

## 3.2 The mean accuracy scores through all the itterations.

In [22]:
print("The avarage accuracy of AdaBoost is :", np.mean(scores_ab))
print("The avarage accuracy of Random Forest is :", np.mean(scores_rf))
print("The avarage accuracy of Decision Trees is :", np.mean(scores_dt))
print("The avarage accuracy of Logistic Regression is :", np.mean(scores_lr))

The avarage accuracy of AdaBoost is : 0.763668430335097
The avarage accuracy of Random Forest is : 0.7865961199294532
The avarage accuracy of Decision Trees is : 0.7072310405643739
The avarage accuracy of Logistic Regression is : 0.8042328042328042


## 4. Comparing the previous resultsto the (Sklean cross_val_score) method

### 1- AdaBoost Folds

In [23]:
cross_val_score(AdaBoostClassifier(), np.array(features), np.array(target), cv= kf)

array([0.44444444, 0.88888889, 0.77777778, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.77777778,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.88888889, 0.66666667, 0.55555556, 0.55555556, 0.66666667,
       0.88888889, 1.        , 1.        , 0.88888889, 0.88888889,
       0.88888889, 0.33333333, 0.88888889, 0.77777778, 0.66666667,
       1.        , 0.77777778, 0.44444444, 1.        , 0.44444444,
       0.66666667, 1.        , 0.77777778, 0.88888889, 0.77777778,
       0.66666667, 0.77777778, 0.55555556, 0.88888889, 1.        ,
       1.        , 0.        , 1.        , 1.        , 0.        ,
       0.88888889, 0.77777778, 0.22222222, 1.        , 0.66666667,
       0.88888889, 0.33333333, 0.77777778, 0.55555556, 0.88888889,
       0.        , 0.        , 1.        ])

### 2- Random Forest Folds

In [24]:
cross_val_score(RandomForestClassifier(), np.array(features), np.array(target), cv= kf)

array([0.33333333, 1.        , 0.88888889, 1.        , 0.88888889,
       1.        , 1.        , 0.88888889, 0.77777778, 0.88888889,
       1.        , 0.88888889, 1.        , 1.        , 1.        ,
       0.66666667, 0.77777778, 1.        , 0.77777778, 0.88888889,
       1.        , 1.        , 1.        , 0.77777778, 0.88888889,
       1.        , 0.44444444, 0.44444444, 0.66666667, 0.55555556,
       0.88888889, 1.        , 0.77777778, 1.        , 0.66666667,
       0.33333333, 0.88888889, 0.77777778, 1.        , 0.88888889,
       1.        , 0.66666667, 0.88888889, 1.        , 1.        ,
       1.        , 0.        , 0.88888889, 1.        , 0.11111111,
       1.        , 0.66666667, 0.        , 1.        , 0.66666667,
       0.88888889, 0.33333333, 1.        , 0.66666667, 0.77777778,
       0.        , 0.        , 1.        ])

### 3- Decision Trees Folds

In [25]:
cross_val_score(DecisionTreeClassifier(), np.array(features), np.array(target), cv= kf)

array([0.44444444, 0.77777778, 0.88888889, 1.        , 0.88888889,
       0.88888889, 1.        , 0.77777778, 0.88888889, 0.77777778,
       0.77777778, 0.77777778, 0.44444444, 0.66666667, 0.77777778,
       0.88888889, 0.77777778, 1.        , 0.55555556, 0.55555556,
       1.        , 0.88888889, 0.88888889, 0.66666667, 0.77777778,
       0.77777778, 0.55555556, 0.55555556, 0.77777778, 0.66666667,
       1.        , 0.77777778, 0.55555556, 0.88888889, 0.33333333,
       0.66666667, 0.77777778, 0.77777778, 1.        , 0.77777778,
       0.88888889, 0.66666667, 0.66666667, 0.88888889, 0.88888889,
       1.        , 0.11111111, 0.88888889, 0.77777778, 0.11111111,
       1.        , 0.77777778, 0.33333333, 0.88888889, 0.44444444,
       1.        , 0.33333333, 0.66666667, 1.        , 0.66666667,
       0.        , 0.        , 1.        ])

### 4- Logistic Regression Folds (arranged folds)

In [26]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='auto'), np.array(features), np.array(target),cv= kf)

array([0.44444444, 0.88888889, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.22222222, 0.88888889,
       1.        , 1.        , 0.77777778, 0.44444444, 0.55555556,
       1.        , 1.        , 1.        , 0.44444444, 1.        ,
       0.66666667, 1.        , 0.33333333, 1.        , 1.        ,
       1.        , 0.33333333, 1.        , 0.55555556, 0.66666667,
       0.77777778, 1.        , 1.        , 1.        , 1.        ,
       0.77777778, 1.        , 1.        , 0.77777778, 1.        ,
       0.88888889, 1.        , 0.66666667, 1.        , 1.        ,
       1.        , 0.        , 1.        , 1.        , 0.33333333,
       1.        , 1.        , 0.        , 0.77777778, 1.        ,
       1.        , 0.77777778, 1.        , 0.66666667, 1.        ,
       0.        , 0.        , 1.        ])

### 4- Logistic Regression Folds (not arranged folds)

In [27]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='auto'), np.array(features), np.array(target),cv= gkf, groups = groups)

array([1.        , 1.        , 0.55555556, 1.        , 0.33333333,
       1.        , 1.        , 1.        , 0.33333333, 1.        ,
       0.66666667, 1.        , 0.44444444, 1.        , 1.        ,
       0.55555556, 0.77777778, 0.44444444, 0.77777778, 1.        ,
       1.        , 0.88888889, 0.22222222, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.88888889,
       0.66666667, 1.        , 0.        , 1.        , 0.        ,
       1.        , 0.66666667, 1.        , 0.77777778, 1.        ,
       1.        , 0.77777778, 0.        , 1.        , 1.        ,
       0.33333333, 1.        , 0.        , 1.        , 1.        ,
       1.        , 1.        , 0.66666667, 1.        , 0.88888889,
       1.        , 0.77777778, 1.        , 1.        , 0.77777778,
       1.        , 1.        , 0.44444444])

## Mean scores for each predictive model

### 1- AdaBoost

In [28]:
np.mean(cross_val_score(AdaBoostClassifier(), np.array(features), np.array(target), cv= kf))

0.7619047619047619

### 2- Random Forest

In [29]:
np.mean(cross_val_score(RandomForestClassifier(), np.array(features), np.array(target), cv= kf))

0.7865961199294532

### 3- Decision Trees

In [30]:
np.mean(cross_val_score(DecisionTreeClassifier(), np.array(features), np.array(target), cv= kf))

0.7160493827160493

### 4- Logistic Regression (arranged)

In [31]:
np.mean(cross_val_score(LogisticRegression(solver='liblinear',multi_class='auto'), np.array(features), np.array(target),cv= kf))

0.8042328042328042

### 4- Logistic Regression (not arranged)

In [32]:
np.mean(cross_val_score(LogisticRegression(solver='liblinear',multi_class='auto'), np.array(features), np.array(target),cv= gkf, groups = groups))

0.8042328042328042

### Conclusion :

* Python's Sklearn has a majority of methods that can allow us to perform the cross validation methods (Group K-fold CV) & (K-fold CV) without a need to do it manually using a function or a for loop to itterate through the training and testing chosen indeces. 